name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        labels: |
          :muscle: Effort: 1
          :wrench: Type: Maintenance
          :star2: Priority: Medium
          :eyes: Status: Review Needed
        release-type: node
        package-name: release-please-action